spring:
  profiles:
    active: local

sms:
  toast:
    url: https://api-sms.cloud.toast.com/
    app-key: ENC(6RJ/b4qil0Y8tFxhSnIMZQvmxzCrEEw7DAx2uZ3x6W668sB6sxQ3SNgBj5lxiG6yD4n4NPgr2lZPEEVrbUlBlg==)
    secret-key: ENC(ab1yfScRuzyplJ3e2xpdYX8qW5j4ZBjwmG4nKekbVp1NdJ/zV9BL7UO8P/68lrB9)

---
spring:
  profiles: local
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
---